### ISSUE TITLE
MRI segmentation 

### ISSUE THREAD

**Issue by Ahmed-ballah** [FengheTan9/CMUNeXt#2]
I am interested for your works

I used MRI with nii file , how can I implement according to your project , please guide me .

thanks you

**Comment by FengheTan9** [comment]
Thanks for focusing on our work.
1. Save your MRI files in the same file format.
2. Modify following code (dataloader/dataset.py) to read nii to numpy：
`image = cv2.imread(os.path.join(self._base_dir, 'images', case + '.png'))`
`label = cv2.imread(os.path.join(self._base_dir, 'masks', '0', case + '.png'), cv2.IMREAD_GRAYSCALE)[..., None]`

**Comment by Ahmed-ballah** [comment]
Thanks you for replay

After spilt data , when run the training 

python main.py --model  CMUNeXt  --base_dir   /CMUNeXt/data/busi  --train_file_dir busi_train.txt --val_fi
le_dir busi_val.txt

the result shown the  Segmentation fault 

how to fix it?

**Comment by FengheTan9** [comment]
Show error message please.

**Comment by Ahmed-ballah** [comment]
<img width="748" alt="Untitled" src="https://github.com/FengheTan9/CMUNeXt/assets/120349201/4bcfd17a-0aef-4bb6-bff3-4e3f47162108">

**Comment by FengheTan9** [comment]
You can try to run on the BUSI data set first. 
This may be a segmentation fault (not image segmentation), it is an error reported by the linux kernel.

**Comment by Ahmed-ballah** [comment]
![image](https://github.com/FengheTan9/CMUNeXt/assets/120349201/4d9225d8-a643-44f4-a16b-c91effb42f

I do that , but still as same problem
